FROM python:3
COPY requirements.txt .
RUN pip3 install -r requirements.txt

COPY . .
RUN python manage.py makemigrations
RUN python manage.py migrate
EXPOSE 8000 587
CMD ["python","manage.py","runserver","0.0.0.0:8000"]