# Generated by Django 4.1.1 on 2022-10-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_function', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastpatient',
            name='address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='pastpatient',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pastpatient',
            name='phone',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='pastpatient',
            name='state',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pastpatient',
            name='time',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pastpatient',
            name='email',
            field=models.CharField(default='', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='pastpatient',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pastpatient',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
